# G1_21j config
robot_name: "g1_21j"
checkpoint_path: "/home/amy/gitrepo/robot_rl/logs/g1_policies/stair/g1/2025-06-12_16-24-03/exported/policy.pt"
num_obs: 330
num_action: 21
period: 0.8                   # s
dt: 0.02                      # 50 Hz
ang_vel_scale: 0.25
command_scale: [2, 2, 2]
qpos_scale: 1
qvel_scale: 0.05 #0.1
action_scale: 0.25
height_map_scale: 1.0         # Height sensor enabled for stair scenario
def_ang_order: "mj"
default_angles: [-0.42, 0, 0, 0.81, -0.4, 0,
                  -0.42, 0, 0, 0.81, -0.4, 0,
                  0,
                  0.1, 0.27, 0, 1.2,
                  0.1, -0.27, 0, 1.2]
log: true
log_dir: "logs"
scene: "stairs_scene"