config: hzd_gl_policy
onboard:
  # --------------------------------- #
  # ----------- Controller ---------- #
  # --------------------------------- #
  control:
  # ----- Low Level Controller ----- #
    - pkg: g1_control
      params:
        hf_policy_folders: [
          # "running_clf_sym/2026-02-11_19-27-52_T2_running_more_cmd_goal_cond_sym_reward_sym",

          # "running_clf_sym/2026-02-13_17-50-41_running_P_from_QR_init_on_walking_sym",
          # "running_clf_sym/2026-02-14_09-51-15_T0_running_P_higher_torque_pen_all_on_ref_sym",

          # "running_clf_sym/2026-02-15_11-20-21_T2_running_higher_tor_l2_higher_tor_lim_sym",
          # "running_clf_sym/2026-02-15_11-25-13_T1_running_higher_l2_10_lim_sym",

          # "running_clf_sym/2026-02-23_10-41-24_T5_running_ABL_CLF_GOAL_ADJ_DYNAMIC_HD_ALL_sym",
          # "running_clf_sym/2026-02-25_14-32-28_running_CLF_GOAL_ADJ_DYNAMIC_HD_ALL_NEW_USD_FIXES_sym",

          # New policies
          "running_clf_sym/2026-02-25_16-21-38_T0_running_ABL_CLF_GOAL_ADJ_DYNAMIC_HD_ALL_sym", #-- Looks good in sim
          # "running_clf_sym/2026-02-25_16-24-12_T1_running_ABL_CLF_GOAL_ADJ_DYNAMIC_HD_ALL_more_torque_pen_sym", # --- Not quite as clean but works
          # "running_clf_sym/2026-02-27_11-09-13_T1_running_ABL_CLF_GOAL_ADJ_DYNAMIC_HD_ALL_more_torque_pen_more_goal_sym",

          # Walking
          "walking_clf_sym/2026-02-20_15-18-54_T0_walking_more_robustness_sym",
          # "walking_clf_sym/2026-02-16_17-51-02_T0_walking_tuning_sym",
          # "walking_clf_sym/2026-02-15_18-02-52_walking_some_start_run_sym",
          # "walking_clf_sym/2026-02-11_13-14-31_walking_new_changes_test_sym",
        ]
        hf_repo_ids: [
          "zolkin/robot_rl",
          "zolkin/robot_rl",
        ]
        behavior_names: [
          "running",
          "walking",
        ]
        behavior_buttons: [
          2,                  # x
          1,                  # b
        ]
        vel_thresholds: [
          10.0, 1.1,
          1.1, -1.1
        ]
        START_IN_SIM: true
        init_behavior: "walking"
        hf_repo_id: "zolkin/robot_rl"
        log: true
        log_decimation: 1 # relative to the control callback
        config_name: "sim_config_hzd_gl.yaml"
      executable: g1_controller
      # callback_groups:
      publishers:
        - ros_parameter: pub_ctrl_setting
          topic: /obelisk/g1/low_level_control
          history_depth: 10
          callback_group: None
      subscribers:
        - ros_parameter: sub_est_setting
          topic: /obelisk/g1/est_state
          history_depth: 10
          callback_group: None
        # ----- High Level Command subscriber ----- #
        - ros_parameter: sub_vel_cmd_setting
          topic: /obelisk/g1/high_level_ctrl
          history_depth: 10
          callback_group: None
        # ----- Joystick subscriber ----- #
        - ros_parameter: sub_joy_setting
          topic: /obelisk/g1/joy_passthrough
      timers:
        - ros_parameter: timer_ctrl_setting
          timer_period_sec: 0.02    # 50 Hz
          callback_group: None
 # ----- High Level Controller ----- #
    - pkg: g1_control
      executable: high_level_control
      params:
        v_x_min: -1.1
        v_x_max: 3.7
        v_y_max: 0.75
        w_z_max: 0.4
        vel_increment: 0.1
        kp_yaw: 0.75 #3.5 #3.0
        kd_yaw: 0.0 #0.1
        kp_y: 0.5 #1.0 #2.0 #5.0
        kd_y: 0.0 #0.3
        use_odom: True
        log_odom: True
        vel_increment_start: 0.0
        traj_dt: 0.3333333
        traj_nodes: 10
      # callback_groups:
      publishers:
        - ros_parameter: pub_ctrl_setting
          topic: /obelisk/g1/high_level_ctrl
          history_depth: 10
          callback_group: None
        - ros_parameter: pub_joy_feedback
          topic: /obelisk/g1/joy_feedback
          history_depth: 10
        - ros_parameter: pub_odom_data
          topic: /obelisk/g1/odom
          history_depth: 10
        - ros_parameter: pub_traj_data
          topic: /obelisk/g1/traj_data
          msg_type: PoseArray
          history_depth: 10
      subscribers:
        # ----- Joint Encoder subscriber ----- #
        - ros_parameter: sub_joint_encoders
          topic: /obelisk/g1/joint_encoders
          msg_type: ObkJointEncoders
          history_depth: 10
          callback_group: None
        # ----- Joystick subscriber ----- #
        - ros_parameter: sub_est_setting
          topic: /obelisk/g1/joy_passthrough
          history_depth: 10
          callback_group: None
        # ----- Odom subscriber ----- #
        - ros_parameter: sub_odom_setting
          topic: /obelisk/g1/head_odom
          history_depth: 10
          callback_group: None
        # ----- Unitree High Level subscriber ----- #
        - ros_parameter: sub_vel_cmd_setting
          topic: /obelisk/g1/unitree_high_level_ctrl
          history_depth: 10
          callback_group: None
        # ----- Lidar IMU subscriber ----- #
        - ros_parameter: sub_lidar_imu
          topic: /obelisk/g1/lidar_imu
          msg_type: Imu
          history_depth: 10
          callback_group: None
        # ----- MPC Command Subscriber ----- #
        - ros_parameter: sub_mpc_setting
          topic: /mpc_command
          msg_type: Twist
          history_depth: 10
      timers:
        - ros_parameter: timer_ctrl_setting
          timer_period_sec: 0.05    # 20 Hz
          callback_group: None
  # ----- MPC Controller ----- #
    - pkg: mpc
      executable: mpc_node
      params:
        problem_name: right
        dt: 0.4
        v_max: [2.5, 0.75, 0.4]
        v_min: [-0.5, -0.75, -0.4]
        # dv_max: [0.2, 0.1, 0.1] #[0.1, 0.05, 0.05]
        N: 25
        Q: [10, 1, 0.0]
        R: [0.4, 0.5, 0.1]
        alpha: 0.1 #0.7
        delta: 5 #0.2
        v_norm_max: 3.0 #0.8
        plan_topic: /obelisk/g1/mpc_path
        path_topic: /obelisk/g1/robot_path
        joy_topic: /obelisk/g1/joy_passthrough
        btn_idle: 0     # A
        btn_zeroing: 1  # B
        btn_run: 3      # Y
        obst_topic: /obelisk/g1/mpc_obstacles
        # Zeroing parameters
        zeroing_position_threshold: 0.05
        zeroing_stable_duration: 2.0
        zeroing_check_period: 0.1
        zeroing_timeout: 30.0
        odom_frame: odom
        camera_init_frame: camera_init
        logging: False
      # callback_groups:
      publishers:
      # ----- High Level Control ----- #
        - ros_parameter: pub_ctrl_setting
          topic: /mpc_command
          history_depth: 10
          callback_group: None
      subscribers:
      # ----- subscribe to odometry ----- #
        - ros_parameter: sub_est_setting
          topic: /obelisk/g1/odom
      timers:
        - ros_parameter: timer_ctrl_setting
          timer_period_sec: 0.4
          callback_group: None
  # ----- High Level/Execution FSM Controller ----- #
    - pkg: obelisk_unitree_cpp
      executable: obelisk_unitree_joystick
      params:
        v_x_scale: 3.6
        v_y_scale: 0.75
        w_z_scale: 0.4

        vel_cmd_yaw: 13  # RY
      # callback_groups:
      publishers:
      # ----- Execution FSM ----- #
        - ros_parameter: pub_exec_fsm_setting
          topic: /obelisk/g1/exec_fsm
          history_depth: 10
          callback_group: None
      # ----- High Level Control ----- #
        - ros_parameter: pub_ctrl_setting
          topic: /obelisk/g1/unitree_high_level_ctrl
          history_depth: 10
          callback_group: None
      subscribers:
      # ----- Joystick Passthrough ----- #
        - ros_parameter: pub_joy_passthrough_setting
          topic: /obelisk/g1/joy_passthrough
      # ----- Joystick subscriber ----- #
        - ros_parameter: sub_est_setting
          topic: /obelisk/g1/joy
      timers:
        - ros_parameter: timer_ctrl_setting
          timer_period_sec: 100  # Control callback is not being used
          callback_group: None
  # --------------------------------- #
  # ----------- Estimator ----------- #
  # --------------------------------- #
  estimation:
    - pkg: g1_control
      executable: g1_estimator
      # callback_groups:
      publishers:
        - ros_parameter: pub_est_setting
          topic: /obelisk/g1/est_state
          msg_type: EstimatedState
          history_depth: 10
          callback_group: None
      subscribers:
        - ros_parameter: sub_joint_encoders
          topic: /obelisk/g1/joint_encoders
          msg_type: ObkJointEncoders
          history_depth: 10
          callback_group: None
        - ros_parameter: sub_pelvis_imu
          topic: /obelisk/g1/pelvis_imu
          msg_type: Imu
          history_depth: 10
          callback_group: None
        - ros_parameter: sub_odom
          topic: /obelisk/g1/odom
          msg_type: Odometry
          history_depth: 10
          callback_group: None
      timers:
        - ros_parameter: timer_est_setting
          timer_period_sec: 0.001
          callback_group: None
  # sensing:
  # --------------------------------- #
  # ------------- Robot ------------- #
  # --------------------------------- #
  robot:
    - is_simulated: True
      pkg: robot_sim
      executable: simulation
      params:
        ic_keyframe: standing
      # callback_groups:
      timers:
        - ros_parameter: timer_true_sim_state_setting
          history_depth: 10
          timer_period_sec: 0.002
          callback_group: None
      subscribers:
        - ros_parameter: sub_ctrl_setting
          topic: /obelisk/g1/low_level_control
          history_depth: 10
          callback_group: None
      sim:
        - ros_parameter: mujoco_setting
          robot_pkg: g1_model
          model_xml_path: scene.xml
          # model_xml_path: cylinder.xml
          sensor_settings:
          # ---------- Joint Encoders ---------- #
          - topic: /obelisk/g1/joint_encoders
            dt: 0.001
            msg_type: ObkJointEncoders
            sensor_names:
            # ---------- Joint Positions ---------- #
              left_hip_pitch_joint_pos_sensor: jointpos
              left_hip_roll_joint_pos_sensor: jointpos
              left_hip_yaw_joint_pos_sensor: jointpos
              left_knee_joint_pos_sensor: jointpos
              left_ankle_pitch_joint_pos_sensor: jointpos
              left_ankle_roll_joint_pos_sensor: jointpos

              right_hip_pitch_joint_pos_sensor: jointpos
              right_hip_roll_joint_pos_sensor: jointpos
              right_hip_yaw_joint_pos_sensor: jointpos
              right_knee_joint_pos_sensor: jointpos
              right_ankle_pitch_joint_pos_sensor: jointpos
              right_ankle_roll_joint_pos_sensor: jointpos

              waist_yaw_joint_pos_sensor: jointpos
              # waist_roll_joint_pos_sensor: jointpos
              # waist_pitch_joint_pos_sensor: jointpos

              left_shoulder_pitch_joint_pos_sensor: jointpos
              left_shoulder_roll_joint_pos_sensor: jointpos
              left_shoulder_yaw_joint_pos_sensor: jointpos
              left_elbow_joint_pos_sensor: jointpos
              left_wrist_roll_joint_pos_sensor: jointpos
              left_wrist_pitch_joint_pos_sensor: jointpos
              left_wrist_yaw_joint_pos_sensor: jointpos

              # left_hand_thumb_0_joint_pos_sensor: jointpos
              # left_hand_thumb_1_joint_pos_sensor: jointpos
              # left_hand_thumb_2_joint_pos_sensor: jointpos
              # left_hand_middle_0_joint_pos_sensor: jointpos
              # left_hand_middle_1_joint_pos_sensor: jointpos
              # left_hand_index_0_joint_pos_sensor: jointpos
              # left_hand_index_1_joint_pos_sensor: jointpos

              right_shoulder_pitch_joint_pos_sensor: jointpos
              right_shoulder_roll_joint_pos_sensor: jointpos
              right_shoulder_yaw_joint_pos_sensor: jointpos
              right_elbow_joint_pos_sensor: jointpos
              right_wrist_roll_joint_pos_sensor: jointpos
              right_wrist_pitch_joint_pos_sensor: jointpos
              right_wrist_yaw_joint_pos_sensor: jointpos

              # right_hand_thumb_0_joint_pos_sensor: jointpos
              # right_hand_thumb_1_joint_pos_sensor: jointpos
              # right_hand_thumb_2_joint_pos_sensor: jointpos
              # right_hand_middle_0_joint_pos_sensor: jointpos
              # right_hand_middle_1_joint_pos_sensor: jointpos
              # right_hand_index_0_joint_pos_sensor: jointpos
              # right_hand_index_1_joint_pos_sensor: jointpos
            # ---------- Joint Velocities ---------- #
              left_hip_pitch_joint_vel_sensor: jointvel
              left_hip_roll_joint_vel_sensor: jointvel
              left_hip_yaw_joint_vel_sensor: jointvel
              left_knee_joint_vel_sensor: jointvel
              left_ankle_pitch_joint_vel_sensor: jointvel
              left_ankle_roll_joint_vel_sensor: jointvel

              right_hip_pitch_joint_vel_sensor: jointvel
              right_hip_roll_joint_vel_sensor: jointvel
              right_hip_yaw_joint_vel_sensor: jointvel
              right_knee_joint_vel_sensor: jointvel
              right_ankle_pitch_joint_vel_sensor: jointvel
              right_ankle_roll_joint_vel_sensor: jointvel

              waist_yaw_joint_vel_sensor: jointvel
              # waist_roll_joint_vel_sensor: jointvel
              # waist_pitch_joint_vel_sensor: jointvel

              left_shoulder_pitch_joint_vel_sensor: jointvel
              left_shoulder_roll_joint_vel_sensor: jointvel
              left_shoulder_yaw_joint_vel_sensor: jointvel
              left_elbow_joint_vel_sensor: jointvel
              left_wrist_roll_joint_vel_sensor: jointvel
              left_wrist_pitch_joint_vel_sensor: jointvel
              left_wrist_yaw_joint_vel_sensor: jointvel

              # left_hand_thumb_0_joint_vel_sensor: jointvel
              # left_hand_thumb_1_joint_vel_sensor: jointvel
              # left_hand_thumb_2_joint_vel_sensor: jointvel
              # left_hand_middle_0_joint_vel_sensor: jointvel
              # left_hand_middle_1_joint_vel_sensor: jointvel
              # left_hand_index_0_joint_vel_sensor: jointvel
              # left_hand_index_1_joint_vel_sensor: jointvel

              right_shoulder_pitch_joint_vel_sensor: jointvel
              right_shoulder_roll_joint_vel_sensor: jointvel
              right_shoulder_yaw_joint_vel_sensor: jointvel
              right_elbow_joint_vel_sensor: jointvel
              right_wrist_roll_joint_vel_sensor: jointvel
              right_wrist_pitch_joint_vel_sensor: jointvel
              right_wrist_yaw_joint_vel_sensor: jointvel

              # right_hand_thumb_0_joint_vel_sensor: jointvel
              # right_hand_thumb_1_joint_vel_sensor: jointvel
              # right_hand_thumb_2_joint_vel_sensor: jointvel
              # right_hand_middle_0_joint_vel_sensor: jointvel
              # right_hand_middle_1_joint_vel_sensor: jointvel
              # right_hand_index_0_joint_vel_sensor: jointvel
              # right_hand_index_1_joint_vel_sensor: jointvel
          # # ---------- Torso IMU ---------- #
          # - topic: /obelisk/g1/torso_imu
          #   dt: 0.001
          #   msg_type: ObkImu
          #   sensor_names:
          #     torso_imu_acc_sensor: accelerometer
          #     torso_imu_gyro_sensor: gyro
          #     torso_imu_quat_sensor: framequat
          # ---------- Pelvis IMU ---------- #
          - topic: /obelisk/g1/pelvis_imu
            dt: 0.001
            msg_type: Imu
            sensor_names:
              pelvis_imu_acc_sensor: accelerometer
              pelvis_imu_gyro_sensor: gyro
              pelvis_imu_quat_sensor: framequat
          # # ---------- Pelvis Mocap ---------- #
          # - topic: /obelisk/g1/pelvis_pose
          #   dt: 0.00416   # 240 Hz
          #   msg_type: PoseStamped
          #   sensor_names:
          #     base_mocap_pos_sensor: framepos
          #     base_mocap_quat_sensor: framequat
          # # ---------- Torso Mocap ---------- #
          # - topic: /obelisk/g1/torso_pose
          #   dt: 0.00416   # 240 Hz
          #   msg_type: PoseStamped
          #   sensor_names:
          #     torso_mocap_pos_sensor: framepos
          #     torso_mocap_quat_sensor: framequat
          # # ---------- Torso Camera Odometry ---------- #
          # - topic: /obelisk/g1/torso_odom
          #   dt: 0.005
          #   msg_type: Odometry
          #   sensor_names:
          #     torso_camera_pos_sensor: framepos
          #     torso_camera_orientation_sensor: framequat
          #     torso_camera_velocimeter: velocimeter
          #     torso_camera_gyro: gyro
          # ---------- Head Lidar Odometry ---------- #
          - topic: /obelisk/g1/head_odom
            dt: 0.01 #0.1
            msg_type: Odometry
            sensor_names:
              head_lidar_pos_sensor: framepos
              head_lidar_orientation_sensor: framequat
              head_lidar_velocimeter: velocimeter
              head_lidar_gyro: gyro
          # ---------- Lidar IMU ---------- #
          - topic: /obelisk/g1/lidar_imu
            dt: 0.001
            msg_type: Imu
            sensor_names:
              lidar_imu_acc_sensor: accelerometer
              lidar_imu_gyro_sensor: gyro
              lidar_imu_quat_sensor: framequat
          # - topic: /cloud_registered_body
          #   dt: 0.1
          #   msg_type: PointCloud2
          #   config_path: /home/zolkin/robot_rl/transfer/obelisk/g1_control/configs/lidar/mid360.yaml
          #   sensor_names:
          #     scan_pos_sensor: framepos
          # viz_geoms:
          #   dt: 1
          #   # ----- Stair scene ----- #
          #   stair1: box
          #   stair2: box
          #   stair3: box
          #   # ----- Tile scene ----- #
          #   tile1: box
          #   tile2: box
          #   tile3: box
          #   tile4: box
          #   tile5: box
          #   tile6: box
          #   tile7: box
          #   tile8: box
          #   tile9: box
  # --------------------------------- #
  # -------------- Viz -------------- #
  # --------------------------------- #
  viz:
    on: False #True
    viz_tool: foxglove
    viz_nodes:
      - pkg: robot_viz
        executable: robot_viz
        robot_pkg: g1_model
        urdf: g1_hand.urdf
        robot_topic: robot_description
        subscribers:
          - ros_parameter: sub_viz_est_setting
            topic: /obelisk/g1/est_state
            history_depth: 10
            callback_group: None
            non_obelisk: False
        publishers:
          - ros_parameter: pub_viz_joint_setting
            topic: joint_states
            history_depth: 10
            callback_group: None
        timers:
          - ros_parameter: timer_viz_joint_setting
            timer_period_sec: 0.01
            callback_group: None
  # --------------------------------- #
  # ----------- Joystick ------------ #
  # --------------------------------- #
  joystick:
    on: True
    pub_topic: /obelisk/g1/joy
    sub_topic: /obelisk/g1/joy_feedback
